import type { Article } from './articles';

/**
 * The two issues that were on the site before articles moved into Supabase.
 * Kept in the repo so a build still emits both article pages when the query
 * fails or the table has not been seeded yet (see loadArticles in articles.ts).
 * Once supabase/articles-seed.sql has been applied these rows are dead weight
 * for normal builds, but they stay as the offline-build safety net.
 */
export const FALLBACK_ARTICLES: Article[] = [
  {
    slug: 'whose-world-cup',
    title: '⚽🌎🏆 Whose World Cup? Where Chicago’s Global South Gathers to Watch',
    category: 'Culture',
    pubDate: '2026-06-09T11:41:14+00:00',
    heroImage: 'images/newsletter/whose-world-cup/hero.webp',
    heroAlt:
      'Illustrated poster of a referee with braided hair blowing a whistle and holding up a red card reading ‘¡Fuera ICE!’, next to a soccer ball and the words ‘No ICE in the Cup’, framed by blue and white tilework.',
    heroCreditHtml:
      '<a href="https://www.instagram.com/p/DYF8Je0Ga4E/" target="_blank" rel="noopener noreferrer">Header art credit: Shaina Lu</a>',
    description:
      'FIFA says football unites the world. A Brown Line guide to where Chicago’s Global South diasporas gather to watch the 2026 World Cup, and to the borders shaping who gets to play.',
    tags: ['Fútbol', 'World Cup 2026', 'Watch parties', 'Immigration and borders', 'Neighborhood guides', 'Cross-cultural'],
    summary:
      'FIFA promises that football unites the world, while travel bans, denied visas, and ICE at the gates decide who actually gets in. A route through the Chicago rooms where Global South diasporas gather to watch the opening week of the 2026 World Cup.',
    bodyHtml: `<p>LAST UPDATED: Thurs. June 11, 2026</p>
<p>“<a href="https://inside.fifa.com/campaigns/football-unites-the-world" target="_blank" rel="noopener noreferrer">Football Unites the World</a>,” FIFA likes to say. The 2026 World Cup kicks off today with a utopian promise: that for a few weeks, the world will gather around “the beautiful game.”</p>
<p>But long before the first whistle, the tournament has revealed the borders that make that promise a farce. The biggest World Cup in history — 48 teams and 104 matches, and three host countries — is being staged across North America while war, visa politics, travel bans, <a href="https://www.theguardian.com/us-news/2026/jun/01/ice-fifa-world-cup-immigrant-rights" target="_blank" rel="noopener noreferrer">ICE on security duty</a>, and <a href="https://www.espn.com/soccer/story/_/id/48947095/2026-fifa-world-cup-sticker-shock-ugly-cost-beautiful-game-grand-event" target="_blank" rel="noopener noreferrer">astronomical ticket prices</a> shape who gets to play, who gets to watch, and who gets left outside the gates.</p>
<p>Nothing illustrates our unequal world order better than this year’s World Cup: The U.S. is hosting a majority of the games, while fully or partially banning entry for fans from Iran, Haiti, Côte d’Ivoire, and Senegal — or simply denying visas to people from other countries with little explanation, including athletes and other team members. As one immigration lawyer put it: “The <a href="https://www.bbc.com/news/articles/cx212p8r28eo" target="_blank" rel="noopener noreferrer">visa system is the invisible goalie</a> of the World Cup.” </p>
<p>For many teams from the Global South, the U.S. border is their first opponent. That was the case for the Iraqi team, who flew into Chicago last Friday for Tuesday’s <a href="https://www.reuters.com/sports/soccer/iraq-conclude-world-cup-preparations-with-defeat-venezuela-2026-06-10/" target="_blank" rel="noopener noreferrer">tune-up match against Venezuela</a> in Bridgeview, ahead of their first World Cup appearance in 40 years — only for their <a href="https://www.wbez.org/immigration/2026/06/09/world-cup-soccer-immigration-trump-ice-border-patrol-iran-iraq-team-ohare-trump-administration" target="_blank" rel="noopener noreferrer">star striker, Aymen Hussein, to be questioned</a> for nearly seven hours at O’Hare before finally being allowed entry. Their <a href="https://abc7chicago.com/post/photographer-traveling-iraq-soccer-team-denied-entry-us-chicago-ohare-airport-amid-fifa-world-cup-games-cbp/19248612/" target="_blank" rel="noopener noreferrer">photographer, Talal Salah, was not so lucky</a>, however, and was ultimately deemed “inadmissible.”</p>
<p>Meanwhile, in the wake of U.S. and Israeli strikes on Iran, Iran’s team is not being allowed to fully base on its “host’s” soil. The players’ <a href="https://www.bbc.com/news/articles/cgmpmp89dvro" target="_blank" rel="noopener noreferrer">visas were delayed until the last minute, while several staff were denied</a>, and they’re <a href="https://www.theguardian.com/football/2026/jun/06/iran-world-cup-visas-mexico" target="_blank" rel="noopener noreferrer">only allowed into the U.S. around the day</a> of their matches, which is why they’re forced to base across the border in Mexico for the tournament. Their fans won’t get in at all: <a href="https://www.espn.com/soccer/story/_/id/49008116/world-cup-tickets-iran-fans-revoked-says-country-federation" target="_blank" rel="noopener noreferrer">days before kickoff, their entire ticket allocation was revoked</a>. </p>
<p>The <a href="https://www.nytimes.com/2026/06/09/world/africa/somali-referee-world-cup-us-entry-omar-artan.html?unlocked_article_code=1.pVA.avH7.TgWE3RG5z3B6&amp;smid=url-share" target="_blank" rel="noopener noreferrer">U.S. even turned away a referee from Somalia</a> last weekend: Omar Artan, the first Somali ever chosen to officiate a World Cup match, arrived in Miami on a valid visa, only to be ruled “inadmissible due to vetting concerns.” Somalia is on the travel ban, too. A man who <a href="https://www.aljazeera.com/news/2026/6/8/us-confirms-denying-entry-to-somali-referee-set-to-take-part-in-world-cup" target="_blank" rel="noopener noreferrer">once navigated around explosions</a> to reach his hometown pitch in Mogadishu almost made it all the way to football’s biggest field — only to be sent home.</p>
<p>And Palestine, as usual, isn’t here at all — unable to qualify amid occupation, blockade, and what <a href="https://www.ohchr.org/en/press-releases/2025/09/israel-has-committed-genocide-gaza-strip-un-commission-finds" target="_blank" rel="noopener noreferrer">UN investigators have documented as genocide</a>, with more than 500 of its footballers killed, and its bombed-out stadiums turned into detention sites and refugee camps. But Palestinians have a word for refusing defeat — <em>sumud</em>, steadfastness — and <a href="https://goldengoal.world/2026/06/05/as-long-as-there-is-football/" target="_blank" rel="noopener noreferrer">as long as there’s football, they’ll never stop playing</a>, writes Gazan journalist Mohammed R. Mhawish. Meanwhile, as always, the diaspora and allies in Chicago are making sure Palestine remains visible.</p>
<p>Chicago has always been a living map of the Global South, with immigrant neighborhoods and community spaces throwing their doors open to welcome the world that the government won’t. We may not be hosting any World Cup games, but the city’s diasporas are carrying the Cup’s real meaning.</p>
<p>That’s why this guide isn’t trying to list every World Cup party in Chicago, or send you to whatever sports bar discovered soccer last week. The Brown Line curates the gatherings where the game carries real meaning — for diaspora communities often carrying grief from their homelands while being treated as a threat in their new home of the U.S. These are the immigrant-owned restaurants and bars, pickup crews, grassroots groups, art spaces and community halls where soccer is bigger than FIFA — where it’s as much an extension of who you are as the language, music, family rituals, and food you were raised on.</p>
<p>So this week, see for yourself how football <em>really</em> unites our world — not through a <a href="https://www.politico.com/news/2026/01/17/state-department-secret-playbook-sports-trump-00735496" target="_blank" rel="noopener noreferrer">government playbook</a> of <a href="https://www.theguardian.com/football/2026/apr/27/world-cup-bonanza-of-sportswashing-donald-trump-ice-human-rights" target="_blank" rel="noopener noreferrer">sportswashing</a>, but through the people who play the game, argue over it and still scoot over to save you a seat. Because there’s always room for one more on our team.</p>
<hr class="transit-divider-slot" />
<h2>🚉⚽🌎 Global game, local stops (Tues. June 9 – Wed. June 17)</h2>
<p>This special edition of The Brown Line guide focuses on the World Cup’s opening week. The Brown Line will keep tracking Chicago’s diaspora watch parties and footy-adjacent events throughout the tournament, alongside other arts, culture, and community events rooted in Chicago’s Global South diasporas. RSVP, location, time, and other details are at the links. If you don’t see a specific watch party here, <a href="https://www.meninred97.com/checking-out-soccer-house-chicagos-soccer-exclusive-bar/" target="_blank" rel="noopener noreferrer">Soccer House</a> has every match, all tournament long.</p>
<p>For now, we’re staying on the pitch: Pick a screen, take a side, and save somebody a seat!</p>
<p><em>🎧 Global soundtrack for the ride: Chicago’s very own football fanatic </em><a href="https://www.instagram.com/dj_mochi" target="_blank" rel="noopener noreferrer">DJ Mochi</a> <em>curated a</em> <a href="https://music.apple.com/us/playlist/mochis-world-cup-playlist/pl.u-leylWlRSjL4qvJz" target="_blank" rel="noopener noreferrer">World Cup playlist just for The Brown Line</a><em>. It’s an international pregame mix, whether you’re headed to a watch party, hosting from home, or just trying to feel the world a little closer.</em></p>
<div class="embed-frame">
<iframe src="https://embed.music.apple.com/us/playlist/mochis-world-cup-playlist/pl.u-leylWlRSjL4qvJz" title="Mochi's World Cup playlist on Apple Music" height="450" loading="lazy" allow="autoplay *; encrypted-media *; fullscreen *; clipboard-write"></iframe>
</div>
<h2>Tues. June 9: Warmup! 🏋️‍♂️</h2>
<ul>
  <li>🇮🇶🇻🇪 <a href="https://www.seatgeekstadium.com/events-ticket/venezuela-vs-iraq-international-soccer-match/" target="_blank" rel="noopener noreferrer">Iraq vs. Venezuela tune-up match (Bridgeview)</a>: A rare chance to see two Global South teams meet on a Chicago-area pitch, in a southwest suburb where Arab, Latino and immigrant communities know what it means to carry a country from afar. Iraq arrives as a World Cup qualifier for the first time in 40 years; Venezuela remains the only South American nation that has never reached the tournament. </li>
</ul>
<h3>Thurs. June 11: Opening kickoff at 2 p.m.! 🌎🏆</h3>
<p>The Cup opens with Mexico vs. South Africa, a rematch of <a href="https://en.wikipedia.org/wiki/2010_FIFA_World_Cup_Group_A" target="_blank" rel="noopener noreferrer">the 2010 opener</a> — the first World Cup held on African soil. South Africa’s Siphiwe Tshabalala scored the tournament’s first goal, a stunning strike that sent the host nation (and 85,000 vuvuzelas) into a frenzy before Rafael Márquez silenced them with a 79th-minute equalizer, leading to a 1–1 draw. Sixteen years later, the rematch is on Mexico’s turf — and in Chicago, where Mexican and Latino communities have long made the city their own, it’s bound to feel like a home game. Just pick your neighborhood watch party vibe:</p>
<ul>
  <li>🎧 <a href="https://www.instagram.com/p/DZVw9okGptq/" target="_blank" rel="noopener noreferrer">Sentido at Osito’s Tap (Little Village)</a>: The roving DJ party series bridging Latino past and present cultures lands in La Villita with a deep bench of beloved DJs, plus a dope limited jersey designed by <a href="https://www.instagram.com/brianherrera.art/" target="_blank" rel="noopener noreferrer">Brian Herrera</a> when you buy a drink special.</li>
  <li>✊🏾 <a href="https://www.instagram.com/p/DZGPjh3luwJ/" target="_blank" rel="noopener noreferrer">Build Your Own Nation at Monochrome Brew (Pilsen)</a>: A community-driven watch party that pairs Monochrome’s limited-edition Golazo beer with a bigger mission: Proceeds support the Illinois Coalition for Immigrant and Refugee Rights. The series continues with more watch parties, futsal pickups, and programming centered on teams affected by travel bans, including Haiti, Iran, Côte d’Ivoire and Senegal.</li>
  <li>🧘🏽‍♀️ <a href="https://www.instagram.com/p/DZVWUgyRoNk/" target="_blank" rel="noopener noreferrer">Latina Sweat Project (Pilsen)</a>: Family-friendly fun at the wellness studio: live DJ, games, soccer-themed face painting, cotton candy, aguas frescas, and your $10 registration keeps the space going for the community.</li>
  <li>🇲🇽 <a href="https://www.tixr.com/groups/ramovatheatre/events/mexico-vs-south-africa-free-world-cup-watch-party-188202" target="_blank" rel="noopener noreferrer">Mexico vs. South Africa at Ramova Theatre (Bridgeport)</a>: Ramova turns its restored movie palace into a fútbol cathedral, with a massive screen, ballet folklórico and the Mexican national anthem before kickoff. Expect big South Side home-crowd energy.</li>
  <li>🇲🇽 <a href="https://www.eventbrite.com/e/los-90-world-cup-tickets-1989420214415" target="_blank" rel="noopener noreferrer">Los 90 at Azul Mariscos (Goose Island)</a>: A nostalgic celebration of Mexican fútbol culture “inspired by the golden era of the World Cup,” with a paletero serving paletas, bandanas, exclusive cups, and live music by Los Ahijados.</li>
  <li>🇿🇦🌇 <a href="https://ma.to/event/eb-wc-opening-match-11-jun-2026" target="_blank" rel="noopener noreferrer">Everywhere Between at Roof on the Wit</a>: If you happen to support South Africa instead, this might be the safest room to say so out loud. Dance to amapiano and Afrobeats on the roof til sunset with South African guest <a href="https://www.instagram.com/kopanoart/" target="_blank" rel="noopener noreferrer">DJ Kopanoart</a> joining headliners <a href="https://instagram.com/dj_mochi" target="_blank" rel="noopener noreferrer">DJ Mochi</a> and <a href="https://www.instagram.com/djiggy" target="_blank" rel="noopener noreferrer">DJ Iggy</a>.</li>
</ul>
<p>🇭🇹 <a href="https://www.eventbrite.com/e/echoes-of-glory-1974-2026-exhibition-opening-and-panel-discussion-tickets-1990830168626" target="_blank" rel="noopener noreferrer">Haitian Soccer in Chicago exhibit opening &amp; panel talk</a>: Not a watch party, but one of the most important World Cup stops on the route. To mark Haiti’s return to the World Cup for the first time since 1974, the Haitian American Museum in Uptown opens “Echoes of Glory,” a limited-run exhibition on Haitian soccer in Chicago — drawing a throughline from that historic run to now, against the bittersweet backdrop of a U.S. travel ban affecting Haitian fans. Panelists include historians and a former player in Chicago’s Haitian soccer league.</p>
<h3>Fri. June 12: The pitch as a canvas 🎨</h3>
<ul>
  <li>⚽🪞 <a href="https://docs.google.com/forms/d/e/1FAIpQLSf-HL8IZ6u2IpEYN-m3sZmRHK4KGi7faiq1hljOz-A4MFGBOg/viewform" target="_blank" rel="noopener noreferrer">Reflections: The Pitch as a Mirror</a>: This West Town art show and salon (Friday-Sunday only) gathers football creatives from around the world to explore how the game reflects the cultures, politics, aesthetics and histories that shape it. The pitch, here, is not an escape from the world but a mirror of it — exactly the right frame for this week.</li>
  <li>🖼️ <a href="https://eliseseigenthaler.com/show/elise-seigenthaler-gallery-the-soccer-show-a-celebration-of-the-world-cup#works" target="_blank" rel="noopener noreferrer">The Soccer Show: A Celebration of the World Cup</a>: Also in West Town, a gallery show of paintings and sculptures features a variety of artists, including Senegalese-born, Chicago-based <a href="https://www.instagram.com/modou_dieng_yacine/" target="_blank" rel="noopener noreferrer">Modou Dieng Yacine</a>. His work explores the intersections of African identity, Western culture, migration, and postcolonial history — fitting for a show about the world’s game in a city shaped by the world.</li>
  <li>🎨 <a href="https://www.instagram.com/p/DZQDWKExc8X/" target="_blank" rel="noopener noreferrer">La Cochera: The World’s Game (Pilsen)</a>: A World Cup art show staged in the <em>cochera</em> — the garage — at Caminos de Michoacán, where a dozen Chicago artists reimagine the tournament as a place where creativity outruns competition, with a karaoke after-party to close. </li>
</ul>
<h3>Sat. June 13: Faith, solidarity, and flags ✊🏾</h3>
<ul>
  <li>🕌 <a href="https://www.eventbrite.com/e/world-cup-watch-party-qatar-vs-switzerland-tickets-1990057805467" target="_blank" rel="noopener noreferrer">Qatar vs. Switzerland at the Downtown Islamic Center</a> (the Loop): A community watch party hosted by Bayan and open to all, as Qatar — the first Arab and Muslim nation to host a World Cup, where Palestinian flags filled the stands in 2022 — opens its campaign.</li>
  <li>🇲🇦🇧🇷 <a href="https://www.instagram.com/p/DZSuv4zRrg7/" target="_blank" rel="noopener noreferrer">Cheer for Morocco against Brazil with USPCN</a> (Bridgeview): Join the U.S. Palestinian Community Network as it cheers on Morocco’s Atlas Lions — the first Arab and African team to reach a World Cup semifinal in 2022, and whose players raised the Palestinian flag in Qatar. They’re up against five-time champions Brazil. A watch party with a side of activism.</li>
  <li>🇭🇹<a href="https://www.instagram.com/p/DZYWKVThC0Z/" target="_blank" rel="noopener noreferrer">Haiti vs. Scotland at Lior’s Cafe</a> (Washington Heights): Cheer for Haiti on the far South Side with authentic fritay, a DJ and BYOB energy. Wear your colors — it’s Haiti’s first World Cup in 52 years, and with the travel ban shutting out fans from home, this room is the closest thing the Grenadiers have to a home crowd. So come be it.</li>
  <li>🇭🇹 <a href="https://www.eventbrite.com/e/world-cup-watch-party-haiti-vs-scotland-tickets-1990335422828" target="_blank" rel="noopener noreferrer">Haiti vs. Scotland at Kizin Creole Restaurant</a> (Rogers Park): If the South Side’s a trek, the far North Side has you covered. Kizin — “kitchen” in Haitian Creole — is a beloved Haitian restaurant, throwing its doors open for the Grenadiers, with DJ Chacha spinning.</li>
</ul>
<p>(Yes, Saturday’s also Knicks–Spurs Game 5 — a 53-years-in-the-making title chase. But Haiti’s wait is just as old: 52 years since their last World Cup. If you want to feel what half a century of waiting looks like when it finally arrives, it won’t only be on the basketball broadcast.)</p>
<h3>Sun. June 14: The other side of the game</h3>
<ul>
  <li>🎥 <a href="https://www.eventbrite.com/e/screening-mexico-86-tickets-1991243282260" target="_blank" rel="noopener noreferrer">Screening: México 86 at the National Museum of Mexican Art</a>: Starring Diego Luna, <em>México 86</em> satirizes the backroom dealing, ambition and political maneuvering that helped Mexico land the 1986 World Cup. A fitting watch as Mexico becomes the first country to host the men’s Cup for a third time — and a reminder that FIFA drama is never new.</li>
  <li>⚽ <a href="https://www.instagram.com/p/DZI7GvHBGMO/" target="_blank" rel="noopener noreferrer">Favella Football Club training clinic</a>: Get on the pitch yourself at these co-ed Sunday morning sessions at Harrison Park to sharpen your skills, with socializing and giving back off the field too. </li>
</ul>
<h3>Mon. June 15: The matchday is the story</h3>
<p>No official diaspora watch party on the board yet, but Monday’s matches are too Brown Line-coded to skip:</p>
<ul>
  <li>11 a.m.: Cape Verde — a tiny island nation built by migration — makes its World Cup debut against Spain.</li>
  <li>2 p.m.: Egypt brings one of the Arab world’s deepest football traditions against Belgium.</li>
  <li>5 p.m.: Saudi Arabia faces Uruguay.</li>
  <li>8 p.m.: Iran vs. New Zealand.</li>
</ul>
<p>Where to watch: No dedicated space yet — try the all-tournament anchors (Recess, Soccer House, Big City Pickle). Know of an Iranian, Egyptian or Cape Verdean party? Send it our way.</p>
<h3>Tues. June 16: Colonizers, former colonies, and comebacks</h3>
<p>Still no official watch parties announced, but that certainly does not mean your tio’s living room doesn’t count. The slate is heavy with history today: </p>
<ul>
  <li>2 p.m.: France vs. Senegal is the one to circle — empire and colony, bound by a shared language, and the rematch of Senegal’s stunning 2002 upset. </li>
  <li>5 p.m.: Iraq vs. Norway: the Lions of Mesopotamia’s first World Cup in 40 years, the same team that landed at O’Hare to a seven-hour interrogation, now stepping from that back room onto the world stage. </li>
  <li>8 p.m.: Argentina vs. Algeria — football royalty against a team whose flag still carries the weight of Algeria’s fight for independence from France.</li>
  <li>11 p.m.: Jordan’s World Cup debut against Austria, one more SWANA team claiming a place in a tournament where belonging is being tested at every gate.</li>
</ul>
<p>Where to watch: The same anchors — but Tuesday’s the day to ask around. The best room for Iraq’s return, or France-Senegal, won’t have a marketing budget; it’ll be a restaurant where this match has been circled for weeks. Hosting one? Send it our way.</p>
<h3>Wed. June 17: Ghana, Panama, and pickup in Pilsen</h3>
<p>Wednesday finally has a room of its own. DR Congo opens against Portugal at noon and Uzbekistan makes its debut against Colombia late — but the heart of the day is in Pilsen:</p>
<ul>
  <li>🇬🇭🇵🇦 <a href="https://www.instagram.com/p/DZVw7ShPsU3/" target="_blank" rel="noopener noreferrer">Ghana vs. Panama</a> (Pilsen): The day’s marquee match gets the full community treatment — a watch party with Pilsen United, Favella Football Club, and Build Your Own Nation, part of a World Cup series around neighborhood soccer, the travel-ban teams and immigrant rights, with proceeds to ICIRR. Kickoff 6 p.m.</li>
  <li>⚽ <a href="https://www.instagram.com/p/DZVw7ShPsU3/" target="_blank" rel="noopener noreferrer"><strong>Favella FC Coed Futsal Pickup</strong></a> (Reyes Park, Pilsen): When you’re done yelling at the screen, get your own touches in — Wednesday-evening pickup from the same Pilsen crew. Just show up and play.</li>
</ul>
<p>Send this to the friend who needs a place to watch, the cousin who suddenly cares about soccer every four years, and the person who knows the real game has always been bigger than FIFA.</p>
<p>That’s all for our football route for this World Cup opening week. Until next time: Save somebody a seat!</p>
<p>With gratitude,<br />G 🚉🤎✊🏾</p>`,
  },
  {
    slug: 'back-in-service-for-good',
    title: '🚊Back in Service — For Good!',
    category: 'Global South',
    pubDate: '2026-05-29T05:00:00+00:00',
    heroImage: 'images/newsletter/back-in-service-for-good/hero.png',
    heroAlt:
      'The Brown Line newsletter cover art: a retro wordmark on a dark brown field, trailed by rainbow transit stripes.',
    description:
      'The Brown Line is back: scenes from the months it went quiet, a service update, answers to reader FAQs, and an express ride into Summertime Chi.',
    tags: ['Community organizing', 'Mutual aid', 'Arts and culture', 'Neighborhood guides', 'Behind the newsletter', 'Cross-cultural'],
    summary:
      'The Brown Line comes back into service with the gatherings it caught while the newsletter was quiet, from Palestinian concrete maps to a solidarity circle for Sudan. Plus a service update, answers to the questions readers keep asking, and an express ride into Summertime Chi.',
    bodyHtml: `<p><em>“It’s been a long time…I shouldn’t have left you, without a dope beat to step to…”</em></p>
<p>Since I launched <em>The Brown Line</em> in July 2025 and sent only five issues, over 400 people have subscribed to this newsletter — entirely via word of mouth — and I’m truly grateful for every single reader of these words that I painstakingly string together (without the help of AI, btw!). </p>
<p>But it’s been too long! </p>
<p>This comeback issue has four parts: </p>
<ul>
  <li><strong>Missed connections:</strong> Scenes from when <em>The Brown Line</em> was quiet</li>
  <li><strong>Service update:</strong> What I’ve been up to</li>
  <li><strong>Know before you ride:</strong> Answers to some FAQs</li>
  <li><strong>Next stops:</strong> An express ride into Summertime Chi</li>
</ul>
<h2>🚆 Missed Connections: Scenes From When The Brown Line Was Quiet</h2>
<p>I won’t pretend the city paused while I did. <em>The Brown Line</em> has been quiet since September, but Chicago’s Global South diasporas have stayed in motion. Our communities have been responding to genocide, imperialism, displacement, surveillance, immigration raids, and crises here and in our homelands — not only through protest, but through gatherings around art exhibits, poetry readings, food, film screenings, farming, concerts, markets, movement, workshops, fundraisers, teach-ins, and community care. Here are a few of my favorite recent stops:</p>
<ul>
  <li>🇵🇸🎨 Amid what major human rights organizations call genocide in Gaza and Israel’s ongoing illegal military occupation of Palestinian land, Palestinians in Chicago are processing their trauma and resisting eradication through powerful works of art. At an inspiring gathering with fellow creatives, <a href="https://creativemornings.com/talks/koorsoo-with-linda-abdullah/1" target="_blank" rel="noopener noreferrer">Linda Abdullah shared</a> her meticulous research into historical maps and how she <a href="https://www.lindaabdullah.io/concrete-maps" target="_blank" rel="noopener noreferrer">stitched concrete (!) onto canvas</a> to depict Israeli settlements replacing Palestinian villages. I’m in awe of how much labor it takes to make erasure visible — and how much love it takes to keep creating anyway. Linda even figured out how to <a href="https://www.lindaabdullah.io/shifting-grounds" target="_blank" rel="noopener noreferrer">make concrete tiles move</a>, to show the ground shifting beneath her people’s feet. </li>
  <li>💃🏃‍♂️ But Chicago’s Palestinians aren’t standing alone. <a href="https://www.instagram.com/latinxsforpalestinechi" target="_blank" rel="noopener noreferrer">Latinxs for Palestine</a> teamed up with the <a href="https://www.instagram.com/chipalfilmfest/" target="_blank" rel="noopener noreferrer">Chicago Palestine Film Fest</a> to bring the legendary <a href="https://www.el-funoun.org/" target="_blank" rel="noopener noreferrer">El-Funoun dabke troupe</a> from the West Bank all the way to Pilsen’s <a href="https://www.instagram.com/18casadecultura/" target="_blank" rel="noopener noreferrer">18th Street Casa de Cultura</a> to teach a joyful <a href="https://www.instagram.com/p/DQba_cFDWUt/" target="_blank" rel="noopener noreferrer">dance workshop</a>. The <a href="https://www.instagram.com/p/DXUtawBDRwO/" target="_blank" rel="noopener noreferrer">solidarity kept moving</a> through a group run led by the <a href="https://www.instagram.com/chi.mrc/" target="_blank" rel="noopener noreferrer">Chicago Muslim Run Club</a> that ended with treats at the aptly-named <a href="https://www.instagram.com/anticonquistacafe" target="_blank" rel="noopener noreferrer">Anticonquista Cafe</a>.    </li>
  <li>🥬📦 As ICE raids spread fear across the city, <a href="https://www.instagram.com/chefmanofrom18th/" target="_blank" rel="noopener noreferrer">Chef Manny Mendoza</a> turned up the heat on his popular weekly <a href="https://southsideweekly.com/best-revolutionary-weeknight-utopia-pueblo-night-market-in-pilsen/" target="_blank" rel="noopener noreferrer">Pueblo Market for mutual aid</a> and sanctuary for undocumented vendors in Pilsen. Manny launched <a href="https://www.instagram.com/pueblo_eats/" target="_blank" rel="noopener noreferrer">Pueblo Eats</a>, a rapid-response initiative to deliver fresh local produce to people who risked arrest if they left home. </li>
  <li>☕💙 And along with <a href="https://www.instagram.com/casa.de.frutos/" target="_blank" rel="noopener noreferrer">Casa de Frutos</a> and <a href="https://www.instagram.com/cuspchicago/" target="_blank" rel="noopener noreferrer">CUSP</a>, the Pueblo continues to provide for vulnerable neighbors in the food-insecure area of North Lawndale through Farmdega, a food pantry at <a href="https://www.duodevelopment.org/starling" target="_blank" rel="noopener noreferrer">Starling by Duo</a>. More than just the home of Black-owned <a href="https://www.instagram.com/drinkmondaycoffee/" target="_blank" rel="noopener noreferrer">Monday Coffee</a>, the iconic blue Starling building has grown beyond a third place: a “fourth place” for community, an intentional “space for liberation.”  </li>
  <li>🇮🇷🎶 People shaped by displacement know that <a href="https://inthesetimes.com/article/iranian-culture-will-not-be-erased" target="_blank" rel="noopener noreferrer">such spaces can and must be created anywhere</a>, and Iranian-led <a href="https://www.instagram.com/biya.biya.productions/" target="_blank" rel="noopener noreferrer">Biya Biya Productions</a> has been on a construction spree of cultural resistance and <a href="https://swanaalliance.com/about" target="_blank" rel="noopener noreferrer">SWANA</a> community building: organizing musical celebrations of Yalda and Nowruz, drum circles, and bellydance workshops to release trauma stored in the hips.</li>
  <li>🌍📚 Chicago’s African diaspora has its own living cultural archive in <a href="https://www.instagram.com/okrrrika/" target="_blank" rel="noopener noreferrer">Okrika</a>, thoughtfully curating accessible ways of engaging with and preserving <a href="https://www.instagram.com/reel/DVTnyBcjgQE/" target="_blank" rel="noopener noreferrer">African storytelling heritage</a> through cozy reading/listening rooms, film screenings, art objects, and much more. These gatherings feed both my mind and my soul, and I wish for every diaspora to have such nourishment!</li>
  <li>🌼🎨 There are plenty of South Asian events and spaces in Chicago, but few are as warm and lovingly adorned as <a href="https://www.instagram.com/mehalhouse/" target="_blank" rel="noopener noreferrer">Mehal House</a> in Humboldt Park, the art studio of my dear friend <a href="https://www.instagram.com/kweenkaraza/" target="_blank" rel="noopener noreferrer">Eliza Karaza</a>. Every function there feels like walking into a maximalist auntie’s home: Persian rugs, floor-pillow seating perfect for playing Carrom and debating geopolitics over chai and samosas, lanterns and candles, Indian thikri mirrors, hand-painted Arabic calligraphy vases, marigolds, and rose petals scattered everywhere. You’ll leave inspired to create — and if you need guidance, Eliza hosts <a href="https://mehalhouse.com/pages/classes" target="_blank" rel="noopener noreferrer">art classes</a>, too. (Fun fact: Eliza is the one friend who finally got sick of me spamming her with event invites and told me to start this newsletter!)  </li>
  <li>🇸🇩🧘🏽‍♀️ Because Sudanese Chicagoans are too few to carry grief alone, my friends <a href="https://www.instagram.com/zalkalby/" target="_blank" rel="noopener noreferrer">Zaineb Alkalby</a>, an Iraqi American somatic coach, and <a href="https://www.instagram.com/spiritsciencemedicine/" target="_blank" rel="noopener noreferrer">Shirley Montoya</a>, a Peruvian American holistic wellness studio owner, co-hosted a <a href="https://www.instagram.com/p/DSishqBD7g0/" target="_blank" rel="noopener noreferrer">Solidarity Circle for Sudan</a>. The soundbath, meditation, and East African tea ceremony — which raised funds for doctors working in Sudan — was one of the most moving acts of cross-diaspora kinship I witnessed all year. </li>
  <li>☪️🌱 That kind of caretaking travels across Muslim Chicago’s many diasporas, where international grief often becomes local solidarity. From Beirut to Bronzeville, the community is planting trees with the <a href="https://www.instagram.com/chicagomuslimsgreenteam/" target="_blank" rel="noopener noreferrer">Chicago Muslims Green Team</a>, feeding unhoused neighbors with <a href="https://www.instagram.com/chi.care/" target="_blank" rel="noopener noreferrer">Chi-Care</a>, and fighting to save SNAP benefits through a free block party in Englewood with the <a href="https://www.instagram.com/imancentral" target="_blank" rel="noopener noreferrer">Inner-City Muslim Action Network</a>. Eid Mubarak to all!  </li>
</ul>
<p>By now, I hope you see that <em>The Brown Line</em> isn’t just a list of things to do. It’s a way of connecting creative, socially conscious people across a segregated city, elevating what’s underground, documenting the artists, organizers, healers, and neighbors preserving culture, creating refuge, and building community — often with little mainstream coverage or institutional support. These are the stories that kept pointing me back to the purpose of <em>The Brown Line</em>.</p>
<hr class="transit-divider-slot" />
<h2>🚆Service update: What I’ve been up to</h2>
<p>Meanwhile, I never stopped thinking about <em>The Brown Line</em>. I did, however, pause writing to spend three months training my mind and body for <a href="https://www.instagram.com/p/DUCiebRjS2Q/" target="_blank" rel="noopener noreferrer">my first-ever boxing match</a> in January! I put my body on the line for charity through Strength in the City Foundation, supporting wellness programs for Black and brown folks on the South and West sides of Chicago (pretty <em>Brown Line</em>-coded, tbh).</p>
<p>Stepping into the ring in front of hundreds of people already felt like a win — but <em>actually</em> winning was a pretty great way to start 2026! Turns out I have enough grit to overcome and achieve almost anything, and I’m addicted to the discipline of training mode — I want to keep fighting, in every sense, inside and outside the ring.  </p>
<p>I’m reminding myself of that as I ride the momentum of that win in other parts of my life. Through <a href="https://localnewsinitiative.northwestern.edu/projects/local-news-accelerator/cohort-program/" target="_blank" rel="noopener noreferrer">Northwestern University’s Local News Accelerator</a> and <a href="https://projectc.biz/going-solo" target="_blank" rel="noopener noreferrer">Project C</a>, I’ve been getting mentorship and support to develop <em>The Brown Line</em>’s editorial vision, audience strategy, and long-term sustainability — without losing the community-rooted spirit that made me start it in the first place. I’m also grateful to <a href="https://www.meetyourneighborchi.com/" target="_blank" rel="noopener noreferrer">Meet Your Neighbor</a> for a small business grant that helped fuel this momentum.</p>
<p>I can’t grow without hiring — specifically a brand designer and someone to make IG and TikTok videos (the bane of my existence!). So please follow <a href="https://www.instagram.com/thebrownlinechi" target="_blank" rel="noopener noreferrer">@TheBrownLineChi</a> on both platforms, and send your portfolio to <a href="mailto:hi@thebrownlinechi.com">hi@thebrownlinechi.com</a> if you’d like to be part of our growth! </p>
<p>Finally, I recently received a scholarship for 200-hour yoga teacher training with the brilliant nonprofit <a href="https://www.instagram.com/latinasweatproject" target="_blank" rel="noopener noreferrer">Latina Sweat Project</a>, whose mission is to diversify wellness and make it accessible to all people. It’s a big time and energy commitment, but something I’m genuinely passionate about. After I’m certified in August, I’m excited to add my own stops to <em>The Brown Line</em> route.</p>
<p>Thank you for believing in me and sticking with me through all sidequests! I promise I’ll always work my hardest to make you proud.</p>
<hr class="transit-divider-slot" />
<h2>🚆Know before you ride: Answers to some FAQs</h2>
<p><em>For more on my editorial values and coverage criteria, see my </em><a href="/standards"><em>Standards &amp; Ethics page</em></a><em>.</em></p>
<h3>What is The Brown Line?</h3>
<p><em>The Brown Line</em> is Chicago’s weekly go-to guide for arts, culture, and community events rooted in Global South perspectives. It’s curated to elevate underground events, artists, and organizations, and aims to build both a cultural archive and connections for socially conscious, diasporic creatives. <em>The Brown Line</em> is cutting through redlining’s legacy to highlight intersectionality and build solidarity across communities. The newsletter is just the first stop. Coming down the line: social videos reviewing art and events, “Passenger of the Week” spotlights, and special events hosted by <em>The Brown Line</em>. </p>
<h3>Does “Brown” mean it’s only for Brown (South Asian/Latino/Arab) people?</h3>
<p>Not at all! The name is a playful nod to the CTA and a reference to all POC (People of Conscience/Cuteness). Allies who show up with curiosity and humility are absolutely welcome aboard!</p>
<h3>What does “Global South” mean?</h3>
<p>“Global South” refers broadly to regions and peoples shaped by imperialism, migration, and unequal global power — including Africa, Latin America, the Caribbean, Southwest Asia and North Africa, South and Southeast Asia, and Indigenous communities around the world. </p>
<p>But it’s less about a map and more about a lens: whose heritage stories, gatherings, foodways, art, grief, joy, and resistance get ignored or treated as secondary in mainstream coverage. </p>
<h3>Is The Brown Line free?</h3>
<p>For now, yes — I want <em>The Brown Line</em> to stay as accessible as possible. A publication for communities often priced out of everything shouldn’t price them out too. The dream is to make <em>The Brown Line</em> sustainable through aligned sponsorships, grants, and optional paid extras — not by putting every good stop behind a turnstile. Any future sponsorships or partnerships will be clearly labeled and won’t determine what I cover.</p>
<h3>How often and when will The Brown Line arrive in my inbox?</h3>
<p>This comeback issue is pulling in midweek — but going forward, catch me arriving in your inbox every Sunday so you can plan your week. I’m committed to keeping this train running on time! </p>
<h3>How do I submit an event?</h3>
<p>Email me at <a href="mailto:hi@thebrownlinechi.com">hi@thebrownlinechi.com</a> with the details: date, time, location, ticket info, access notes, promo image if you have one, and a short description. Submitting doesn’t guarantee inclusion, but I do read everything!</p>
<h3>How can I support The Brown Line?</h3>
<ul>
  <li>Please subscribe to the weekly newsletter — as of this issue, <a href="https://www.thebrownline.co" target="_blank" rel="noopener noreferrer">thebrownline.co</a> is live and fully public, so please also tell your friends to get on board! </li>
  <li>Follow <a href="https://www.instagram.com/thebrownlinechi" target="_blank" rel="noopener noreferrer">@TheBrownLineChi on IG</a> and <a href="https://www.tiktok.com/@thebrownlinechi" target="_blank" rel="noopener noreferrer">TikTok</a> for daily updates. </li>
  <li><a href="mailto:hi@thebrownlinechi.com">Email me</a> feedback, tips, sponsorships, or collab opportunities.</li>
</ul>
<p>Alright, enough platform announcements. Let’s ride!</p>
<hr class="transit-divider-slot" />
<h2>🚆Next stops: An express ride into Summertime Chi (Fri. May 29 - Sun. May 31)</h2>
<h3>Fri. May 29: In honor of my birthday, support your neighborhood cultural center! 🥳</h3>
<ul>
  <li>🎨🌱 <a href="https://givebutter.com/yollocalli-fundraiser-2026-0wpxum" target="_blank" rel="noopener noreferrer">Yollocalli fundraiser party</a>: While some city officials respond to “<a href="https://blockclubchicago.org/2026/05/28/teen-takeovers-revive-chicago-debate-over-curfews-and-parental-accountability/" target="_blank" rel="noopener noreferrer">teen takeovers</a>” on the South and West sides by pushing curfews or penalties for parents, Yollocalli, the National Museum of Mexican Art’s free youth programming initiative, believes that young people need investment, not containment. Pull up to Co-Prosperity for good times, kind people, and <a href="https://www.instagram.com/p/DYzuRzRjsRD/" target="_blank" rel="noopener noreferrer">a model that actually works</a> to help teens thrive.</li>
  <li>🪩💃🏽 <a href="https://segundoruizbelvis.org/event/sentido-takes-over-barrio-bugalu/" target="_blank" rel="noopener noreferrer">Sentido x SRBCC Bugalú night fundraiser</a>: Sentido, the DJ party series bringing young folks to beloved Latino spots across the city, is popping up at the historic Segundo Ruiz Belvis Cultural Center to take over its monthly Barrio Bugalú salsa night. (The bugalú sound was born from Puerto Ricans, Cubans, and Black Americans partying together in the ’60s.) Don’t miss a chance to dance inside a “living archive” of Afro-Latino joy and its cultural home for half a century.</li>
  <li>🏛️🤝 <a href="https://www.heritageasianart.org/event-details-registration/a-community-approach-to-preserve-heritage" target="_blank" rel="noopener noreferrer">Community heritage preservation</a>: If dancing for cultural preservation isn’t for you tonight, you can join artists and archivists at the Heritage Museum of Asian Art to discuss other strategies focused on collective responsibility. Or this could be your pregame move before walking down the street to Co-Prosperity for the Yollocalli party!</li>
</ul>
<h3>Sat. May 30</h3>
<ul>
  <li>🇵🇸⚽🇱🇧 <a href="https://www.instagram.com/p/DYa5FWpMTZr/" target="_blank" rel="noopener noreferrer">Kuffiyeh Cup</a>: Chicago Palestinian organizations are hosting their third soccer tourney and picnic fundraiser, this time for mutual aid in Lebanon. If you didn’t sign up to play, you’re still welcome to picnic and cheer from the sidelines.</li>
  <li>🧵🖼️ <a href="https://www.heritageasianart.org/event-details-registration/closing-reception-stitching-stories-interwoven" target="_blank" rel="noopener noreferrer">Cross-cultural textile art exhibit closing</a>: Normally I avoid recommending the same place twice in one issue, but I don’t want you to miss the last day of the Heritage Museum of Asian Art’s “Stitching Stories: Interwoven,” a collaboration between Asian and African American textile artists reflecting on memory, identity, storytelling, and more. </li>
  <li>🇵🇭🎞️ <a href="https://www.instagram.com/p/DYz7C4uEXM_/" target="_blank" rel="noopener noreferrer">Filipino film, food, and fundraiser</a>: My much-cooler birthday twin, Sarah Conway, is also celebrating the first birthday of Cinemanita, the monthly community cinema club she co-founded at the Chicago Art Department, with a screening of “Manila in the Claws of Light,” a 1975 Filipino classic about migration, labor exploitation, and surviving under the Marcos regime. Come early for fantastic food and to hear diaspora organizers connect the past shown in the film to the recent Philippine military’s killing of 19 people on Negros Island, known as the “Negros 19.”</li>
  <li>🀄🫖 <a href="https://plan.getpie.app/plans/6a2c5e2b-2d81-4924-91fb-9ee42b72e38f" target="_blank" rel="noopener noreferrer">Multilingual mahjong and mochi</a>: What do mahjong tiles clattering in five Asian languages with a community vinyl playlist in the background sound like? Come find out, stuff yourself with mochi, and make friends at this AAPI month social hosted by <a href="https://www.instagram.com/intlcafe.io/" target="_blank" rel="noopener noreferrer">Int’l Cafe</a> (not an actual cafe, but a language exchange club) at <a href="https://www.instagram.com/hai_bayo/" target="_blank" rel="noopener noreferrer">Haibayô</a> (actual cafe and community space) in Argyle.</li>
  <li>🪩🌙 <a href="https://dice.fm/partner/tickets/event/k6d6o8-laylit-30th-may-sleeping-village-chicago-tickets" target="_blank" rel="noopener noreferrer">Shake ass in Arabic (or Persian, or Turkish, etc.)</a>: Touring SWANA dance party Laylit pulls into Sleeping Village for a late-night stop of shaabi, dabke, mahraganat fused with dancehall, techno, hip-hop, and <a href="https://www.instagram.com/p/DYuW-NIAX7i/" target="_blank" rel="noopener noreferrer">a crowd that doesn’t have to translate itself</a> for anyone. Featuring our local DJ friends Saint Susu and A. Parssi.</li>
</ul>
<h3>Sun. May 31</h3>
<ul>
  <li>🇱🇰🥥 <a href="https://plan.getpie.app/plans/5e23bb8b-dc36-4b69-af8d-8610acb2ceaf" target="_blank" rel="noopener noreferrer">Sri Lankan sips</a>: <a href="https://www.instagram.com/nangiscafe/" target="_blank" rel="noopener noreferrer">Nangi’s Cafe</a>, Chicago’s first Sri Lankan coffee cart, is run by a fellow Gemini who also apparently loves blessing everyone this season. What can I say, we’re a generous sign! Catch her pop-up at Chromatic Studio with a mouthwatering menu of coconut crepes stuffed with jaggery, pani pol coconut matcha, jackfruit refreshers, and Ceylon black tea lemonade — then stay for creative coworking, affordable headshots, and free infused drinks.</li>
  <li>📸✨ <a href="https://www.instagram.com/p/DYAGs3cDhqc/" target="_blank" rel="noopener noreferrer">Free community portraits</a>: Photographer <a href="https://www.instagram.com/p/DYSnFDShuUA/" target="_blank" rel="noopener noreferrer">Mercedes Zapata</a> is known for her lush portraits of iconic Chicago poets and artists like Jamila Woods and José Olivarez. Now, she’s turning that same tender eye toward the community, offering free portraits at her Pilsen studio for anyone who wants their joy documented. Bring your graduation outfit, your dog, or anyone you love; snacks and reproductive health resources from Plan C Pills included. Let the record show you smiling!</li>
  <li>🎤🎟️ <a href="https://www.eventbrite.com/e/abby-govindan-pushing-30-comedy-hour-tickets-1984985248312" target="_blank" rel="noopener noreferrer">Abby Govindan is “Pushing 30” + ticket giveaway!</a> The Indian American comedian’s newest standup hour about the horrors of getting older feels personally targeted to every immigrant kid, eldest daughter, overthinker, and Gemini spiraling into a new decade. Go laugh at time, family, ambition, and the very rude fact that we all keep aging. <a href="https://www.instagram.com/abbygovindan/" target="_blank" rel="noopener noreferrer">Abby</a> is actually a good friend and has generously given me two tickets to give away to one <em>Brown Line</em> reader — forward this issue or share the IG post on your story, then <strong>DM or email me a screenshot by 9 a.m. Sun. May 31</strong> to enter. I’ll pick one winner at random.</li>
</ul>
<p>That’s it for this express ride! If <em>The Brown Line</em> has helped you find one new artist, organizer, cafe, dance floor, or friend — please send it to someone who should be riding with us, too.</p>
<p>We are so back, baby. See you Sunday!</p>
<p>With gratitude,<br />G 🚃🤎✊🏾</p>`,
  },
];
